server {
    listen 80;
    server_name _;
    absolute_redirect off;
    root /site/dist;
    index index.html;
    add_header X-Robots-Tag "noindex, nofollow" always;

    location / {
        try_files $uri $uri/ =404;
    }
}
