import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { DEFAULT_MODEL, PROFILE_SCHEMA, SYSTEM_PROMPT, buildModelInput, buildProfilePrompt, enrichRoster, legacyFanVoiceErrors, requestBody, resolveProfileTier, runPlayerProfileGeneration, semanticInputHash, validateGeneratedProfile } from "../src/lib/player-profile-generation.mjs";
import { isDisposablePlayerProfilePath } from "../src/lib/player-profiles.mjs";

const roster=(players=[{id:"jane-doe",name:"Jane Doe",position:"WR",number:11,status:"Active"}])=>({players});
const nfl=(extra={})=>({season:2026,playerStatsSeason:2025,updatedAt:"one",playerSeasonStats:[],...extra});
const directory=[{id:99,full_name:"Jane Doe",position:"WR",jersey_number:11}];
const validOutput=(withStats=false)=>({bio:"Jane Doe joined Seattle's current receiving group with a limited professional record available.",careerHighlights:[],seasonOverview:withStats?"During 2025, Doe produced 50 receiving yards.":null});
const response=(output,usage={input_tokens:100,output_tokens:50,input_tokens_details:{cached_tokens:0},output_tokens_details:{reasoning_tokens:5}})=>({ok:true,json:async()=>({output_text:JSON.stringify(output),usage}),headers:{get:()=>null}});
const rawResponse=(json)=>({ok:true,json:async()=>json,headers:{get:()=>null}});
function tempPaths(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"sfz-profile-"));return{artifactPath:path.join(dir,"profiles.json"),ledgerPath:path.join(dir,"usage.json"),lockPath:path.join(dir,"lock")};}
async function run(options={}){const paths=options.paths||tempPaths();return{paths,summary:await runPlayerProfileGeneration({rosterStore:options.rosterStore||roster(),nflData:options.nflData||nfl(),playerDirectory:options.playerDirectory||directory,existingArtifact:options.existingArtifact||{profiles:{}},...paths,fetchImpl:options.fetchImpl|| (async()=>response(validOutput())),env:options.env||{OPENAI_API_KEY:"test"},warn:options.warn||(()=>{}),tierStore:options.tierStore||{},careerStore:options.careerStore||{},editorialStore:options.editorialStore||{},sleep:async()=>{}})}}

test("model request stays economical and strict",()=>{const body=requestBody(DEFAULT_MODEL,enrichRoster(roster(),nfl(),directory)[0]);assert.equal(DEFAULT_MODEL,"gpt-5.4-mini");assert.equal(body.reasoning.effort,"low");assert.equal(body.text.format.strict,true);assert.equal(body.max_output_tokens,900);});
test("system prompt is professional and factual",()=>{assert.match(SYSTEM_PROMPT,/professional sports-reference prose in neutral third person/);assert.match(SYSTEM_PROMPT,/Use only the facts supplied in the input/);assert.match(SYSTEM_PROMPT,/write less rather than filling space/);});
test("position statistics exclude irrelevant fields",()=>{const p=enrichRoster(roster(),nfl({playerSeasonStats:[{player_id:99,receiving_yards:50,passing_yards:999}]}),directory)[0];assert.deepEqual(p.statistics,{receiving_yards:50});});
test("clean input categorizes facts and removes IDs and sources",()=>{const p={...enrichRoster(roster(),nfl({playerSeasonStats:[{player_id:99,receiving_yards:50}]}),directory)[0],editorialFacts:[{id:"x",type:"acquisition",value:{method:"free agent signing"},source:{url:"x"},reviewedAt:"now"}]},input=buildModelInput(p);assert.deepEqual(input.{team}Career.acquisition,{method:"free agent signing"});assert.equal(input.latestSeason.statistics.receivingYards,50);assert.doesNotMatch(JSON.stringify(input),/"(?:id|source|reviewedAt)"/);});
test("current season appears once",()=>{const p={...enrichRoster(roster(),nfl({playerSeasonStats:[{player_id:99,receiving_yards:50}]}),directory)[0],careerFacts:{recentSeasons:[{season:2025,receivingYards:50},{season:2024,receivingYards:20}]}},input=buildModelInput(p),text=JSON.stringify(input);assert.deepEqual(input.career.recentSeasons,[{season:2024,receivingYards:20}]);assert.equal(text.match(/"receivingYards":50/g).length,1);});
test("tiers have distinct depth and token limits",()=>{const prompts=new Set(),limits=[];for(const tier of ["featured","core","contributor","developmental"]){const p={...enrichRoster(roster(),nfl(),directory)[0],profileTier:tier};prompts.add(JSON.stringify(buildProfilePrompt(p)));limits.push(requestBody(DEFAULT_MODEL,p).max_output_tokens);}assert.equal(prompts.size,4);assert.deepEqual(limits,[2200,1700,1250,900]);});
test("featured prompt requests more biography depth than shorter tiers",()=>{const p=enrichRoster(roster(),nfl(),directory)[0],featured=JSON.stringify(buildProfilePrompt({...p,profileTier:"featured"})),contributor=JSON.stringify(buildProfilePrompt({...p,profileTier:"contributor"})),developmental=JSON.stringify(buildProfilePrompt({...p,profileTier:"developmental"}));assert.match(featured,/250-400 words/);assert.match(contributor,/90-160 words/);assert.match(developmental,/50-100 words/);});
test("Sam remains featured",()=>assert.equal(resolveProfileTier("sam-darnold",{players:{"sam-darnold":{tier:"featured"}}}),"featured"));
test("schema is the requested simple strict JSON",()=>{assert.deepEqual(PROFILE_SCHEMA.required,["bio","careerHighlights","seasonOverview"]);assert.equal(PROFILE_SCHEMA.properties.careerHighlights.items.type,"string");assert.doesNotMatch(JSON.stringify(PROFILE_SCHEMA),/factIds|usedFactIds|profileTier|biography|dek|bullets/);});
test("light validation rejects only contract and safety failures",()=>{const p=enrichRoster(roster(),nfl(),directory)[0];assert.equal(validateGeneratedProfile({...validOutput(),bio:""},p).valid,false);assert.equal(validateGeneratedProfile({...validOutput(),seasonOverview:{}},p).valid,false);for(const copy of ["Our receiver is ready.","AI wrote this.","The prompt says this.","The supplied data says this."])assert.equal(validateGeneratedProfile({...validOutput(),bio:copy},p).valid,false);});
test("legacy fan voice and vague promotional filler are rejected",()=>{for(const copy of ["He is our QB.","Our safety brings energy.","We're excited about our cornerback.","We can't wait to see our new addition.","He could be a game-changer for us.","He will be exciting to watch.","He could make a big impact."])assert.ok(legacyFanVoiceErrors({bio:copy}).length,copy);});
test("claim words and duplicate sentences are accepted",()=>{const p=enrichRoster(roster(),nfl(),directory)[0],o={...validOutput(),bio:"Doe signed and joined Seattle after being drafted. An honor followed. An honor followed.",careerHighlights:["Repeated","Repeated"]};assert.equal(validateGeneratedProfile(o,p).valid,true);});
test("no season data means no season overview",()=>{const p=enrichRoster(roster(),nfl(),directory)[0];assert.equal(validateGeneratedProfile(validOutput(),p).valid,true);assert.equal(validateGeneratedProfile({...validOutput(),seasonOverview:"Generic."},p).valid,false);});
test("representative Sam output passes without IDs",()=>{const fixture=JSON.parse(fs.readFileSync("tests/fixtures/playerProfiles.generated.json","utf8")).profiles["sam-darnold"],careerStore=JSON.parse(fs.readFileSync("src/data/team/player-career-facts.json","utf8")),editorialStore=JSON.parse(fs.readFileSync("src/data/team/player-profile-editorial-facts.json","utf8")),p=enrichRoster(roster([{id:"sam-darnold",name:"Sam Darnold",position:"QB",status:"Active"}]),nfl(),[],()=>{},{players:{"sam-darnold":{tier:"featured"}}},careerStore,editorialStore)[0];assert.doesNotMatch(JSON.stringify(fixture),/factIds|usedFactIds/);assert.equal(validateGeneratedProfile(fixture,p).valid,true);});
test("semantic cache excludes timestamps",()=>{const a={fullName:"X",profileTier:"featured",careerFacts:{careerTotals:{games:1},reviewedAt:"a"}},b={...a,careerFacts:{...a.careerFacts,reviewedAt:"b"}};assert.equal(semanticInputHash(a,DEFAULT_MODEL),semanticInputHash(b,DEFAULT_MODEL));assert.notEqual(semanticInputHash(a,DEFAULT_MODEL),semanticInputHash({...a,careerFacts:{careerTotals:{games:2}}},DEFAULT_MODEL));});
test("unchanged run makes zero requests",async()=>{let calls=0;const paths=tempPaths(),fetchImpl=async()=>{calls++;return response(validOutput())};await run({paths,fetchImpl});const old=JSON.parse(fs.readFileSync(paths.artifactPath));assert.equal((await run({paths,fetchImpl,existingArtifact:old})).summary.requests,0);assert.equal(calls,1);});
test("legacy copy invalidates only the affected cached profile",async()=>{const paths=tempPaths(),p=enrichRoster(roster(),nfl(),directory)[0],hash=semanticInputHash(p,DEFAULT_MODEL),existingArtifact={profiles:{"jane-doe":{...validOutput(),bio:"Our receiver could make a big impact.",generation:{model:DEFAULT_MODEL,promptVersion:"reader-first-player-profile-v4",inputHash:hash}}}};let calls=0;const result=await run({paths,existingArtifact,fetchImpl:async()=>{calls++;return response(validOutput())}});assert.equal(calls,1);assert.equal(result.summary.generated,1);});
test("changed facts invalidate only that player",async()=>{const players=roster([{id:"jane-doe",name:"Jane Doe",position:"WR",status:"Active"},{id:"john-doe",name:"John Doe",position:"WR",status:"Active"}]),dir=[...directory,{id:100,full_name:"John Doe",position:"WR"}],paths=tempPaths();await run({paths,rosterStore:players,playerDirectory:dir,nflData:nfl({playerSeasonStats:[{player_id:99,receiving_yards:50},{player_id:100,receiving_yards:20}]}),fetchImpl:async()=>response(validOutput(true))});const old=JSON.parse(fs.readFileSync(paths.artifactPath));let calls=0,result=await run({paths,rosterStore:players,playerDirectory:dir,nflData:nfl({playerSeasonStats:[{player_id:99,receiving_yards:51},{player_id:100,receiving_yards:20}]}),existingArtifact:old,fetchImpl:async()=>{calls++;return response(validOutput(true))}});assert.equal(calls,1);assert.equal(result.summary.current,1);});
test("spending limits prevent calls",async()=>{const paths=tempPaths(),month=new Date().toISOString().slice(0,7);fs.writeFileSync(paths.ledgerPath,JSON.stringify({months:{[month]:{estimatedCostUsd:20,models:{}}}}));assert.equal((await run({paths})).summary.requests,0);assert.equal((await run({env:{OPENAI_API_KEY:"test",PLAYER_PROFILE_RUN_BUDGET_USD:"0"}})).summary.requests,0);});
test("lock prevents concurrent generation",async()=>{const paths=tempPaths();fs.writeFileSync(paths.lockPath,JSON.stringify({createdAt:new Date().toISOString()}));assert.equal((await run({paths})).summary.lockSkipped,true);});
test("malformed JSON retries once with exact instruction",async()=>{let calls=0,body;await run({fetchImpl:async(_url,options)=>{calls++;if(calls===2)body=JSON.parse(options.body);return calls===1?rawResponse({status:"completed",output_text:"{",usage:{input_tokens:1,output_tokens:1}}):response(validOutput())}});assert.equal(calls,2);assert.match(JSON.stringify(body.input),/Return the same profile as valid compact JSON matching the schema exactly\./);});
test("failed retry preserves old profile",async()=>{const old={profiles:{"jane-doe":{bio:"Last known good"}}};let calls=0,result=await run({existingArtifact:old,fetchImpl:async()=>{calls++;return rawResponse({status:"completed",output_text:"{",usage:{input_tokens:1,output_tokens:1}})}});assert.equal(calls,2);assert.equal(result.summary.preserved,1);assert.equal(old.profiles["jane-doe"].bio,"Last known good");});
test("targeted Sam preserves others and caches",async()=>{const paths=tempPaths(),players=roster([{id:"sam-darnold",name:"Sam Darnold",position:"QB",status:"Active"},{id:"jane-doe",name:"Jane Doe",position:"WR",status:"Active"}]),env={OPENAI_API_KEY:"test",PLAYER_PROFILE_ID:"sam-darnold"},tierStore={players:{"sam-darnold":{tier:"featured"}}},featured=validOutput(),existingArtifact={profiles:{"jane-doe":{bio:"Keep me"}}};let calls=0;await run({paths,rosterStore:players,env,tierStore,existingArtifact,fetchImpl:async()=>{calls++;return response(featured)}});const saved=JSON.parse(fs.readFileSync(paths.artifactPath));assert.equal(saved.profiles["jane-doe"].bio,"Keep me");assert.equal((await run({paths,rosterStore:players,env,tierStore,existingArtifact:saved,fetchImpl:async()=>{calls++;return response(featured)}})).summary.requests,0);assert.equal(calls,1);});
test("disposable path warning remains",()=>assert.equal(isDisposablePlayerProfilePath(path.resolve("runtime/player-profiles/playerProfiles.json"),path.resolve(".")),true));
test("production validator permits incomplete profiles only as reported noindex pages",()=>{const paths=tempPaths();fs.writeFileSync(paths.artifactPath,JSON.stringify({profiles:{}}));const r=spawnSync(process.execPath,["scripts/validate-player-profiles.mjs","--production"],{cwd:path.resolve("."),env:{...process.env,PLAYER_PROFILES_ARTIFACT:paths.artifactPath},encoding:"utf8"});assert.equal(r.status,0);assert.match(r.stdout,/0 indexable/);assert.match(r.stdout,/noindex/);});
test("production validator rejects a declared-indexable incomplete biography",()=>{const paths=tempPaths(),players=JSON.parse(fs.readFileSync("src/data/team/roster.json","utf8")).players,first=players.find((player)=>player.status==="Active");fs.writeFileSync(paths.artifactPath,JSON.stringify({profiles:{[first.id]:{bio:"One biography is not enough.",qualityExpectation:"indexable"}}}));const r=spawnSync(process.execPath,["scripts/validate-player-profiles.mjs","--production"],{cwd:path.resolve("."),env:{...process.env,PLAYER_PROFILES_ARTIFACT:paths.artifactPath},encoding:"utf8"});assert.notEqual(r.status,0);assert.match(r.stderr,/declared-indexable rejection/);});
test("production validator rejects legacy fan voice",()=>{const paths=tempPaths(),players=JSON.parse(fs.readFileSync("src/data/team/roster.json","utf8")).players,first=players.find((player)=>player.status==="Active");fs.writeFileSync(paths.artifactPath,JSON.stringify({profiles:{[first.id]:{bio:"We're excited about our new addition and this deliberately padded profile contains enough words to clear a naive minimum length check."}}}));const r=spawnSync(process.execPath,["scripts/validate-player-profiles.mjs","--production"],{cwd:path.resolve("."),env:{...process.env,PLAYER_PROFILES_ARTIFACT:paths.artifactPath},encoding:"utf8"});assert.notEqual(r.status,0);assert.match(r.stderr,/critical content failure/);});
