// Team-name prefixes, including regional names such as New England.
// Add another TEAM slug here when extending the word template.
export const TEAM_LOCATIONS = Object.freeze({
  bears: 'Chicago',
  bengals: 'Cincinnati',
  bills: 'Buffalo',
  broncos: 'Denver',
  browns: 'Cleveland',
  buccaneers: 'Tampa Bay',
  cardinals: 'Arizona',
  chargers: 'Los Angeles',
  chiefs: 'Kansas City',
  colts: 'Indianapolis',
  commanders: 'Washington',
  cowboys: 'Dallas',
  dolphins: 'Miami',
  eagles: 'Philadelphia',
  falcons: 'Atlanta',
  giants: 'New York',
  jaguars: 'Jacksonville',
  jets: 'New York',
  lions: 'Detroit',
  packers: 'Green Bay',
  panthers: 'Carolina',
  patriots: 'New England',
  raiders: 'Las Vegas',
  rams: 'Los Angeles',
  ravens: 'Baltimore',
  saints: 'New Orleans',
  seahawks: 'Seattle',
  steelers: 'Pittsburgh',
  texans: 'Houston',
  titans: 'Tennessee',
  vikings: 'Minnesota',
});
